### PR TITLE
Add stack2nix updating script

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by domenkozar** [comment]
I really don't want to also build stack2nix, so this is blocked on https://github.com/input-output-hk/stack2nix/issues/94

**Comment by domenkozar** [comment]
Sadly stack -> nix conversion is very impure so committing these files to git is the only way :)

**Comment by roberth** [comment]
It's ok

**Comment by domenkozar** [comment]
Exactly. I'm thinking of dropping/ignoring cabal files now that nixpkgs handles that better since 0f1ebc385d1a6a709900b6893901d6d914fdd5ae

**Pull request merged**
