### PR TITLE
0.1.4

### LINKED ISSUE #157: Fix ChangeLog formatting
I noticed that the  version number formatting is broken.

https://github.com/cachix/cachix/blob/master/cachix/ChangeLog.md

Keep a Changelog uses links to github for the changes between tags. Either add those links or remove the `[]` from the version numbers.

See links at the end: https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/master/CHANGELOG.md

You might also want to rename the file to `CHANGELOG.md` to be consistent with `README.md` and `LICENSE`. That name is commonly used.

### PR DESCRIPTION
**Pull request by domenkozar**
Also fixes #157

### CODE REVIEW

**Comment by domenkozar** [comment]
Blocked on servant implementing streamBody logic.

**Comment by domenkozar** [comment]
Untested in what way? This commit is tested by CI and sdist is generated from the same source.

**Comment by roberth** [comment]
I don't see `haskell.lib.buildFromSdist`, so unless I missed something, we're potentially building from sources that are not actually included in the sdist.

**Comment by domenkozar** [comment]
I'm still a bit confused, build requires haskell code so sdist includes those by default anyway.

In any case, this should be a separate issue and shouldn't block this release as there's no such issue.

**Comment by domenkozar** [comment]
Superseeded by https://github.com/cachix/cachix/pull/163

**Pull request closed without merging**
