### PR TITLE
api: migrate to nix-narinfo and SimpleNarInfo

### PR DESCRIPTION
**Pull request by sorki**
I've pushed it to Hackage as well few minutes ago, marking as draft until it lands in nixpkgs.

### CODE REVIEW

**Comment by sorki** [comment]
Landed in master, is there a way to re-trigger actions?

**Comment by domenkozar** [comment]
You'll need to update haskell.nix pin via `niv update haskell.nix`

**Comment by sorki** [comment]
Looks like it's not yet in `haskell.nix`, we can add overlay or just wait since it's not that important.

**Comment by domenkozar** [comment]
Thanks! It seems like the package is disabled in nixpkgs due to tests failing:

```
Test suite nix-narinfo-samples: RUNNING...

Parse
  roundtrips samples FAILED [1]

Failures:

  test/ParseSpec.hs:24:3:
  1) Parse roundtrips samples
       uncaught exception: IOException of type NoSuchThing
       ./test/samples/0: openFile: does not exist (No such file or directory)

  To rerun use: --match "/Parse/roundtrips samples/"

Randomized with seed 1178892351

Finished in 0.0002 seconds
1 example, 1 failure
```

**Comment by sorki** [comment]
Oh, `extra-source-files` strikes again. Will fix, thanks!

**Comment by sorki** [comment]
Had to bump to master at https://github.com/NixOS/nixpkgs/commit/5897105 since its not in unstable yet.

**Pull request closed without merging**
