### PR TITLE
Add command to list caches

### PR DESCRIPTION
**Pull request by lazamar**
It seems useful to have a command to show what caches I'm using. 
I've wondered that before and had to look at the code to see the directory where the caches are stored.
This PR implements a simple command to show these.

### CODE REVIEW

**Comment by domenkozar** [comment]
Note that this will only show caches that you have generated a key for. You'll see a more complete list on https://app.cachix.org

Are you interested into the caches you own or the caches that you have configured for Nix to use?

**Comment by lazamar** [comment]
The caches Nix can use, so that I can know whether I've added all the caches I need/want.

**Comment by domenkozar** [comment]
In that case it's more complicated, something I want to do as part of https://github.com/cachix/cachix/issues/314

**Comment by domenkozar** [comment]
I'm closing this for now as if we do implement listing of caches, the correct implementation is much more involved.

**Pull request closed without merging**
