### PR TITLE
deps: update hnix-store

### LINKED ISSUE #664: NAR hash mismatch
**Describe the bug**

```
/nix/store/n33v8r9vgs3cmlqhhwj3kcz2frp2x8sv-iina-1.3.5: the computed NAR hash doesn't match the hash returned by the Nix store.

Expected: sha256:12wh4f4zzkvv7b3z9v5z1aihszcbr02v600js5xb0fg02m8q1vhn
Got:      sha256:1cccbw37q5v8ydmm0bl24f0gb10h7qrh3sf755anp9bhjj585gpi
```

This store path can be built on an `aarch64-darwin` machine at:

```
$ nix build nixpkgs/d603719ec6e294f034936c0d0dc06f689d91b6c3#iina
$ realpath ./result
/nix/store/n33v8r9vgs3cmlqhhwj3kcz2frp2x8sv-iina-1.3.5
```

**Version**
 
Running latest master with `hnix-store-core` 0.7.0.0

### PR DESCRIPTION
**Pull request by sandydoo**
Fixes #664.

### CODE REVIEW

**Comment by sandydoo** [comment]
Will need to wait for hnix-store-core 0.8 and hnix-store-nar to be picked up by nixpkgs.

**Comment by Enzime** [comment]
I believe `hnix-store-core_0_8_0_0` is available as of https://github.com/NixOS/nixpkgs/pull/331380

**Comment by Enzime** [comment]
I've made a PR to fix the build for `hnix-store-core_0_8_0_0` at https://github.com/NixOS/nixpkgs/pull/344806

**Comment by Enzime** [comment]
@sandydoo the Nixpkgs PR has been merged now and is available on `nixos-unstable` now

**Comment by sandydoo** [comment]
@domenkozar, merging this will lock us out of `nixpkgs-24.05`, unless we can also backport `hnix-store-core 0.8` and `hnix-store-nar`. Is that an issue?

**Pull request merged**
