### PR TITLE
README: instruct how to install using the new interface

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Review by pingiun — APPROVED** [review]
This is nice. I hope you can also have some way to install the latest release instead of master. Using a branch named `release` would enable `nix profile install github:cachix/cachix/release`

**Comment by domenkozar** [comment]
Does it work with tags? `nix profile install github:cachix/cachix/v0.6.1`

**Comment by pingiun** [comment]
> Does it work with tags? `nix profile install github:cachix/cachix/v0.6.1`

Yes that works but it will not be able to update to the latest release like the other installation method with `nix-env` does. Because if you run `nix profile upgrade` it will still pull the specified tag and see if it updated

**Comment by domenkozar** [comment]
I could use something like https://github.com/marketplace/actions/latest-tag to maintain that automatically

**Comment by pingiun** [comment]
Seems nice!

**Pull request merged**
