### PR TITLE
Add shell autocompletion

### PR DESCRIPTION
**Pull request by roberth**

### CODE REVIEW

**Comment by domenkozar** [comment]
Is there a way to hint that with Cabal or similar? Most users install cachix via nixpkgs, which won't have this change.

**Comment by roberth** [comment]
Nope, I authored the function and such a Cabal feature would make me happy but there isn't one. Seems to be a matter of adding it to nixpkgs like some of the other haskell tools. (Cachix didn't support it at that time, so it probably still needs to be done)

**Comment by domenkozar** [comment]
I guess cabal2nix could detect optparse-applicative in executable dependencies and add the flag, but that's for another day

**Comment by roberth** [comment]
Yeah, such an approach was also discussed here https://github.com/NixOS/nixpkgs/pull/42657

**Pull request merged**
